# ssh-server via ssl (server-mode)
[ssh-server]
connect = 0.0.0.0:2022
#accept = <external-port>
accept = 127.0.0.1:2443

;cert = /etc/ssl/android-rootCA-cert.pem
;key = /etc/ssl/android-rootCA.key

cert = /etc/ssl/uacme/<myhost>/cert.pem
key = /etc/ssl/uacme/private/<myhost>/key.pem
