# socks-proxy server via ssl (server-mode)
[socks-server]

#connect = 127.0.0.1:<socks-port>  # socks(inetd): 7080
#accept = <external-port>  # router: 3443 --> 993

connect = 127.0.0.1:7080
accept = 0.0.0.0:3443

ciphers = PSK
PSKsecrets = /etc/stunnel/secrets.key
