# socks-proxy client via ssl (client-mode)
[proxy-client]
client = yes
connect = <domain-or-ip-remote-server>:<ssl-(ssh)-port>
accept = 127.0.0.1:<internal-ssh-port>

CAfile = /etc/ssl/android-rootCA-cert.pem
verify = 4
