# socks-proxy client via ssl (client-mode)
[proxy-client]
client = yes
connect = <domain-or-ip-remote-server>:<ssl-socks-port>
accept = 127.0.0.1:8123  # internal port
ciphers = PSK
PSKsecrets = /etc/stunnel/client-secrets.key
