# 4081 stream tcp nowait.20 nobody /usr/local/sbin/tcpd /usr/bin/stunnel /etc/stunnel/stunnel-webdavserv.conf
# webdav via ssl (server-mode)
[webdav-server]
connect = 0.0.0.0:4080
accept = 127.0.0.1:4081

;cert = /etc/ssl/android-rootCA-cert.pem
;key = /etc/ssl/android-rootCA.key
# TIP!: rename: localhost --> my-domain
cert = /etc/ssl/uacme/localhost/cert.pem
key = /etc/ssl/uacme/private/localhost/key.pem
