# 127.0.0.1:5901 stream tcp nowait.20 nobody /usr/local/sbin/tcpd /usr/bin/stunnel /etc/stunnel/stunnel-vncserver.conf
# vnc-server via ssl (server-mode)
[vnc-server]
connect = 0.0.0.0:5900
accept = 127.0.0.1:5901

cert = /etc/ssl/uacme/<myhost>/cert.pem
key = /etc/ssl/uacme/private/<myhost>/key.pem
