# git server via ssl (server-mode)
[git-server]
accept = 127.0.0.1:9443
exec = /usr/bin/git
execargs = git daemon --inetd --verbose --export-all --interpolated-path=/srv/git/%H%D /srv/git
cert = /etc/ssl/uacme/<myhost>/cert.pem
key = /etc/ssl/uacme/private/<myhost>/key.pem
