# https://github.com/ryjer/opentracker/raw/master/opentracker.conf.sample
# TIP!: here your announce-url can be like this, e.g.: http://192.168.0.100:6969/announce

listen.tcp 127.0.0.1:6969

#access.whitelist /etc/opentracker/whitelist
#access.whitelist ./whitelist  # if chrootdir
#  or, if opentracker was compiled to blacklist
#access.blacklist ./blacklist

access.stats 127.0.0.1

livesync.cluster.node_ip 127.0.0.1
livesync.cluster.node_ip 192.168.0.0/16

#tracker.rootdir /usr/local/etc/opentracker
#tracker.rootdir /etc/opentracker
tracker.rootdir /var/empty

tracker.user nobody

#tracker.redirect_url https://your.tracker.local/
#tracker.redirect_url http://bt.myhost.server1.test:443/stats
