no-ping  # omit the NET_RAW capability
no-poll
conf-dir=/etc/dnsmasq.d/,*.conf
filterwin2k
filter-rr=ANY,MX,CNAME  # requied newer version
cache-rr=A,AAAA
all-servers
domain-needed
bogus-priv
stop-dns-rebind
rebind-domain-ok=/i2p/onion/lan/local/
no-resolv
cache-size=10000
max-ttl=86400
fast-dns-retry=1000,10000
port=<dns-port>  #enter here a dns port!
listen-address=0.0.0.0
bind-interfaces

# disable DHCP and TFTP on it.
no-dhcp-interface=

addn-hosts=/etc/hosts.d/

log-facility=/var/log/dnsmasq.log
log-queries
