##############################################################################
#  SSH PORT: UserLAnd 2222 / Termux 2022 or another port...                  #
##############################################################################
#<[ip:]port/nameserv> <sock_type> <proto> <flags> <user> <server_path> <args>#

0.0.0.0:8080 stream tcp nowait.40 root /usr/sbin/httpd httpd -i -h /var/www/ -c /etc/httpd.conf

127.0.0.1:7080 stream tcp nowait.60 root /usr/bin/socks socks -d -4 -I

127.0.0.1:5655 stream tcp nowait.20 root /bin/sh sh -l  # to: 127.0.0.1:5655

2222 stream tcp nowait.20 root /usr/sbin/dropbear dropbear -i -r /etc/dropbear/dropbear_ed25519_host_key -s -j -k -T 8
