[Global]
	Name = irc.myhost.server1.test

	AdminInfo1 = Master: Anonymous
	AdminInfo2 = UN, Earth
	AdminEMail = admin@mail.myhost.server1.test

	;HelpFile = :DOCDIR:/Commands.txt

	Info = Online chat

	Listen = ::1,127.0.0.1

	;MotdPhrase = "Hello World!"
	MotdFile = /etc/ircd.motd

	Network = IRCAnonymousChat

	;Password = aabbccddeeff

	PidFile = /run/ngircd.pid

	Ports = 6667

	ServerGID = 65534
	ServerUID = 65534

[Limits]
	;IdleTimeout = 7200

	MaxConnections = 100
	MaxConnectionsIP = 5
	;MaxJoins = 20
	MaxNickLength = 9
	MaxListSize = 50

[Options]
	AllowedChannelTypes = #&+

	;AllowRemoteOper = no

	ConnectIPv6 = no
	ConnectIPv4 = yes

  ;PredefChannelsOnly = yes
	DNS = no
	;Ident = no
	PAM = no

	;MorePrivacy = yes

	;NoticeBeforeRegistration = no

;[Channel]
	;Name = #anonymous-devel
	;Topic = a anonymous project topic
	;Modes = +k
	;KeyFile = /etc/ngircd/channel-devel.key

;[Channel]
  ;Name = #linux
  ;Topic = Distributive's GNU/Linux (english only)
  ;Modes = +k
  ;KeyFile = /etc/ngircd/channel-linux.key

;[Channel]
  ;Name = #gentoo
  ;Topic = Gentoo (english only)

[Channel]
  Name = #alpinelinux
  Topic = Alpine Linux (english only)

;[Channel]
  ;Name = #archlinux
  ;Topic = Archlinux, Manjaro (english only)

;[Channel]
  ;Name = #debian
  ;Topic = Debian, Parrot (english only)

;[Channel]
  ;Name = #slackware

;[Channel]
  ;Name = #openwrt

;[Channel]
  ;Name = #router

[Channel]
  Name = #support

;[Channel]
  ;Name = #earth-en

;[Channel]
  ;Name = #earth-alien

[Channel]
  Name = #unix
  Topic = Unix, Posix, GNU/Linux, FreeBSD, OpenBSD, NetBSD (os,software).
  ;KeyFile = /etc/ngircd/channel-unix.key

;[Channel]
  ;Name = #support-en

[Channel]
  Name = #offtopic

[Channel]
  Name = #earth
  Topic = Language: english, aliens, etc.
  ;Modes = +skr
  ;KeyFile = /etc/ngircd/channel-earth.key
