# BUG: comment a string once begin ^# otherwise be run failed (syntax err)

#debug = info
output = /var/log/stunnel.log

# Some performance tunings
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1

#libwrap = yes  # required build with --enabled-libwrap
delay = no
#failover = prio
#failover = rr

include = /etc/stunnel/conf.d
