# **************************************************************************
# * Global options                                                         *
# **************************************************************************

# It is recommended to drop root privileges if stunnel is started by root
#setuid = nobody
#setgid = nogroup

# PID file is created inside the chroot jail (if enabled)
#pid = /var/run/stunnel.pid

# Debugging stuff (may be useful for troubleshooting)
#foreground = yes
#debug = info
#output = /var/log/stunnel.log

# Some performance tunings
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1

#libwrap = yes  # required build with --enabled-libwrap

# **************************************************************************
# * Include all configuration file fragments from the specified folder     *
# **************************************************************************

include = /etc/stunnel/conf.d
