max_bandwidth = 96000;
welcometext = "Welcome to Anonymous Server!";
certificate = "/etc/umurmur/rootCA.crt";
private_key = "/etc/umurmur/rootCA.key";
password = "aabbccddeeff";
# admin_password = "00aabbccddeeff";   # Set to enable admin functionality.
# ban_length = 0;
# enable_ban = true;
# banfile = "banfile.txt";
# sync_banfile = false;
# show_addresses = true;
max_users = 10;

bindport = 64738;
bindaddr = "0.0.0.0";

username = "nobody";
groupname = "nobody";

logfile = "/var/log/umurmurd.log";

channels = (
	{
		name = "Root";
		parent = "";
		description = "Root channel. No entry.";
		noenter = true;
	},
	{
		name = "Lobby";
		parent = "Root";
		description = "Lobby channel";
	},
	{
		name = "Silent";
		parent = "Root";
		description = "Silent channel";
		silent = true; # Optional. Default is false
	},
	{
		name = "Red team";
		parent = "Lobby";
		description = "The Red team channel";
		allow_temp = true; # Optional. Default is false
	}
);

default_channel = "Lobby";
