# 127.0.0.1:1053 stream tcp nowait.20 nobody /usr/bin/stunnel stunnel /etc/stunnel/stunnel-dnsclient.conf
# dns-client (DoT) via ssl (client-mode)  dnsmasq[2053] --> DoT[853] --> DNS[1053] client
# https://kb.isc.org/docs/aa-01386

[dns-client]
client = yes

connect = 0.0.0.0:853
accept = 127.0.0.1:1053

CAfile = /etc/ssl/certs/ca-certificates.crt
verify = 4
