# irc protocol via ssl (client-mode)

# BUG: comment a string once begin ^# otherwise be run failed (syntax err)

# For irc-client without tls/ssl support
[irc-client]

client = yes

;connect = 127.0.0.1:6697
connect = irc.myhost.server1.test:443
accept = 127.0.0.1:6668

CAfile = /etc/ssl/certs/ca-certificates.crt
