# /etc/smartdns/domainlist-default.conf
# Date: 2026-10-06 13:00 UTC

#address /localhost/0.0.0.0,127.0.0.1
address /config.privoxy.org/127.0.0.1

address /wpad/0.0.0.0
address /wpad.com/0.0.0.0

#address /myhost.server1.test/1.2.3.4,0.0.0.0
#address /myhost.server2.test/1.2.3.4,5.6.7.8

address /github.com/140.82.121.3
address /raw.githubusercontent.com/185.199.111.133
