# /etc/smartdns/bogus-nxdomain.conf
# Date: 2025-03-22 01:00 UTC

# cloudflare error-page
104.21.1.88
172.67.128.242

# amazon parking
199.59.243.223

# sharktech - teddit.com (scam,hijacks-DNS,local-country-ads)
64.32.8.68
