server-name smartdns
user nobody

# For bootstrap
conf-file domainlist-base.conf

bind 127.0.0.1:2053

cache-mem-size 10m
cache-persist yes
cache-file /var/cache/smartdns.cache

log-level warn
log-file /var/log/smartdns.log
log-size 16k
log-num 2

#server 8.8.8.8 -bootstrap-dns
server 127.0.0.1:9053

ip-set -name iplist-bogus -file /etc/smartdns/iplist-bogus-nxdomain.conf
bogus-nxdomain ip-set:iplist-bogus

domain-set -name blacklist-base -type list -file /etc/smartdns/blacklist-base.conf
address /domain-set:blacklist-base/#

#domain-set -name blacklist-lite -type list -file /etc/smartdns/blacklist-1Hosts-Lite.txt
#address /domain-set:blacklist-lite/#

domain-set -name blacklist-oisd-small -type list -file /etc/smartdns/domainswild_small.txt
address /domain-set:blacklist-oisd-small/#
