server-name smartdns
user nobody

# conf-file blacklist-ip.conf

bind 0.0.0.0:2053

cache-mem-size 10m
cache-persist yes
cache-file /var/cache/smartdns.cache

log-level warn
log-file /var/log/smartdns.log
log-size 16k
log-num 2

server 127.0.0.1:9053
