daemon uid = root
daemon gid = root

pid file = /run/rsyncd.pid
lock file = /rsyncd.lock

use chroot = yes
read only = yes

log file = /var/log/rsyncd.log
secrets file = /etc/rsync/auth.conf
motd file = /rsyncd.motd

port = 1873
address = 0.0.0.0

max connections = 10
reverse lookup = no

uid = nobody
gid = nobody

ignore nonreadable = yes
open noatime = yes
transfer logging = yes
timeout = 10

path = /srv/rsync/anyhost/pub
list = no

dont compress = *.gz *.xz *.bz2 *.tgz *.txz *.tbz2 *.cgz *.clz *.cxz
#exclude from = /etc/rsync/some_excludes.lst
exclude = /rsyncd.motd /rsyncd.lock

refuse options = delete delete-*
hosts allow = 192.168.0.0/16 127.0.0.0/29

[pub]
uid = ftp
gid = ftp
path = /srv/rsync/anyhost/pub
comment = public files [sources]
list = yes

[upload]
#auth users = <user>
#write only = yes
#read only = no
path = /srv/rsync/anyhost/upload
comment = upload files (approx 100.0 GB)
